@extends('hact.layouts.print_layout')

@section('content')
<br/>
<input id="print" type="button" value="Print">
<script>
    $('#print').click(function(){
        $(this).hide();
        window.print();
        $(this).show();
    });
    $(document).ready(function(){
        $(".checkup-table span").css("font-weight","bold");
        $(".checkup-table td").css("vertical-align","top");
    });
</script>
<br/>
<br/>

<div class="row">
    <div class="medium-12 columns">
        <table class="checkup-table" width="100%">
            <tr>
                <th colspan="2" style="text-align: center">
                    Medical Abstract
                </th>
            </tr>
            <tr>
                <td style="text-align: center">
                    Patient: {{ $medical_abstract->Patient->code_name }}
                </td>
                <td style="text-align: center">
                    Date: {{ $medical_abstract->date->format('M/d/Y') }}
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <pre style="text-align: left">{{ $medical_abstract->body }}</pre>
                </td>
            </tr>
            <tr>
                <td colspan="1">
                    &nbsp;
                </td>
                <td colspan="1">
                    <div>Generated By:<br/>
                        Name: {{ Auth::user()->name }}<br/>
                        Email: {{ Auth::user()->email }}
                    </div>
                </td>
            </tr>
        </table>
    </div>
</div>

@endsection


