
@extends("hact.layouts.print_layout")

@section("content")
<br/>
<input id="print" type="button" value="Print">
<script>
	$('#print').click(function(){
		$(this).hide();
		window.print();
		$(this).show();
	});
</script>
<br/>
<br/>
<div class="row">
	<div class="large-12 column">
		<h4>OBGyne Childbirth Report</h4>
	</div>
</div>
<div class="row">
	<div class="large-6 column">
		<strong>Currently Pregnant: </strong> {{ $result }}
	</div>
	<div class="large-6 column">
		<strong>Date :</strong> {{ $from }} - {{ $to }}
	</div>
</div>

<br />
<div class="row">
	<div class="large-12 column">
		<table width="100%">
			<tbody>
				<th width="25%">UI Code</th>
				<th width="25%">SACCL</th>
				<th width="20%">Code Name</th>
				<th width="20%">Nationality</th>
				<th width="10%">Gender</th>
			</tbody>
			<tbody>
			@foreach($obgyne as $row)
				<tr>
					<td>{{ $row->Patient->ui_code }}</td>
					<td>{{ $row->Patient->saccl_code }}</td>
					<td>{{ $row->Patient->code_name }}</td>
					<td>{{ $row->Patient->nationality }}</td>
					<td>{{ $row->Patient->gender_format }}</td>
				</tr>
			@endforeach
			<tr>
				<td colspan="2">
					&nbsp;
				</td>
				<td colspan="3">
					<div>Generated By:<br/>
						Name: {{ Auth::user()->name }}<br/>
						Email: {{ Auth::user()->email }}
					</div>
				</td>
			</tr>
			</tbody>
		</table>
	</div>
</div>

@endsection
