
@extends("hact.layouts.print_layout")

@section("content")

<div class="row">
	<div class="large-12 column text-center top">
	<strong>HIV Counseling and Testing(HCT) Monthly Report
	<br>
	Corazon Locsin Montelibano Memorial Regional Hospital</strong>
	<br>
	Reporting Period: {{ $from }} to {{ $to }}
	</div>
</div>
<br />
<div class="row">
	<div class="large-12 column">
		<table width="100%">
			<thead>
				<tr class="head">
					<th width="25%">Type of Clients</th>
					<th width="25%">No. of Patients/Clients who underwent Pre-Test Counseling</th>
					<th width="20%">No. of Patient/Clients Tested</th>
					<th width="20%">No. of Patients/ Clients who received results and underwent Post-Test Counseling</th>
					<th width="10%">No. of Patients/ Clients diagnosed with HIV</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>MARP*(SW, Client of SW, MSM, IDU or combination of risks)</td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td>MW*</td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td>HCW with OE*</td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td>Pregnant</td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td>Children(<18yo)</td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td>Others</td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td>TOTAL</td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td>No. of HCW provided with PEP*</td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td>Remarks:5 in others no identifier risky behaviors</td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td colspan="3">
						&nbsp;
					</td>
					<td colspan="2">
						<div>Generated By:<br/>
							Name: {{ Auth::user()->name }}<br/>
							Email: {{ Auth::user()->email }}
						</div>
					</td>
				</tr>
			</tbody>
		</table>
		<div class="row">
			<div class="large-12 column">
				<strong>*MARP</strong>- Most At Risk Popoulation; <strong>MW</strong>Migrant Worker, <strong>HCW</strong> with OE-Healthcare Worker with Occupational Exposure, <strong>PEP</strong>-Given ARV for Post-Exposure Prophylaxis 
			</div>
		</div>
	</div>
</div>
<style type="text/css">
.top{
		margin-top: 50px;
	}

</style>
@endsection