
@extends("hact.layouts.print_layout")

@section("content")
<br/>
<input id="print" type="button" value="Print">
<script>
	$('#print').click(function(){
		$(this).hide();
		window.print();
		$(this).show();
	});
</script>
<br/>
<br/>
<div class="row">
	<div class="large-12 column">
		<h5>{{ $patient_name }} report based on dispense medicine</h5>
		<strong>{{ $from }} - {{ $to }}</strong>
	</div>
</div>

<br />
<div class="row">
	<div class="large-12 column">
		<table width="100%">
			<tbody>
				<tr>
					<th width="40%"><a href="#">Medicines</a></th>
					<th width="15%"><a href="#">No. of Pills</a></th>
					<th width="20%"><a href="#">Date Dispense</a></th>
					<th width="25%"><a href="#">Issued By</a></th>
				</tr>
			</tbody>
			<tbody>
			@foreach($prescription as $row)
				<tr>
					<td>
						@if($row->ARVItems->specified_medicine == '')
							{{ $row->ARVItems->Medicine->name }}
						@else
							{{ $row->ARVItems->specified_medicine }}
						@endif
					</td>
					<td class="text-center">{{ $row->pills_dispense }}</td>
					<td>{{ $row->date_dispense->format('m/d/Y') }}</td>
					<td>{{ $row->User->name }}</td>
				</tr>
			@endforeach
			<tr>
				<td colspan="3">
					&nbsp;
				</td>
				<td colspan="2">
					<div>Generated By:<br/>
						Name: {{ Auth::user()->name }}<br/>
						Email: {{ Auth::user()->email }}
					</div>
				</td>
			</tr>
			</tbody>
		</table>
	</div>
</div>

@endsection