@extends('hact.layouts.print_layout')

@section('content')
    <input id="print" type="button" value="Print">
    <script>
        $('#print').click(function(){
            $(this).hide();
            window.print();
            $(this).show();
        });
    </script>
    <br/>
    <h4 style="color:#4d4d4d">{{ $patient->code_name }} Consultation History</h4>
    @if(count($histories) > 0)
        <div class="row">
            <div class="medium-12 columns">
                <table width="100%" class="responsive">
                    <tr>
                        <th width="10%"></th>
                        <th class="main-column" scope="column" width="15%"><a href="#">Consultation Date</a></th>
                        <th scope="column" width="15%"><a href="#">Follow up Date</a></th>
                        <th width="20%"><a href="#">Chief Complaints</a></th>
                        <th width="25%"><a href="#">General Assessments</a></th>
                        <th width="25%"><a href="#">Medicine Prescribed</a></th>
                        {{--<th width="30%"><a href="#">TB Screening</a></th>--}}
                    </tr>
                    @foreach($histories as $history)
                        <tr>
                            <td>
                            </td>
                            <td class="main-column">{{ $history->checkup_date->format('m/d/Y') }}</td>
                            <td>{{ $history->follow_up_date->format('m/d/Y') }}</td>
                            <td>{{ $history->patient_complaints }}</td>
                            <td>{{ $history->remarks }}</td>
                            <td>
                                @if($history->prescriptions && count($history->prescriptions) > 0)
                                    <table width="100%">
                                        <thead>
                                        <tr>
                                            <td>Medicine</td>
                                            <td>Pills/Day</td>
                                            <td>Dosage</td>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($history->prescriptions as $prescription)
                                            <tr>
                                                @if($prescription->prescription_type == 'arv')
                                                    <td>{{ ($prescription->Medicine ) ?  $prescription->Medicine->name : '' }}</td>

                                                @elseif($prescription->prescription_type == 'oi' || $prescription->prescription_type == 'others')
                                                    <td>{{ $prescription->specified_medicine }}</td>
                                                @endif
                                                <td>{{ $prescription->pills_per_day }}</td>
                                                <td>{{ $prescription->suggested_dosage }}</td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>

                                @endif
                            </td>
                        </tr>
                    @endforeach
                    <tr>
                        <td colspan="3">
                            &nbsp;
                        </td>
                        <td colspan="3">
                            <div>Generated By:<br/>
                                Name: {{ Auth::user()->name }}<br/>
                                Email: {{ Auth::user()->email }}
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>


    @endif
@endsection